# Generated by Django 4.2.4 on 2023-08-22 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='p_ventea',
            new_name='p_venta',
        ),
        migrations.AddField(
            model_name='directorgeneral',
            name='especialidad',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='cuidad',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='', max_length=128),
        ),
    ]
